In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler

In [28]:
data = pd.read_csv('Heart_Dataset.csv')
data

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [29]:
# Min Max Scaling
scalar = MinMaxScaler()
data[['Age', 'RestingBP', 'Cholesterol']] = pd.DataFrame(scalar.fit_transform(data[['Age', 'RestingBP', 'Cholesterol']]))
data = data.rename(columns={
    'Age': 'Age_normalized',
    'RestingBP':'RestingBP_normalized',
    'Cholestrol': 'Cholestrol_normalized'
})
data

,Age_normalized,Gender,ChestPainType,RestingBP_normalized,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,0.244898,M,ATA,0.70,0.479270,0,Normal,172,N,0.0,Up,0
1,0.428571,F,NAP,0.80,0.298507,0,Normal,156,N,1.0,Flat,1
2,0.183673,M,ATA,0.65,0.469320,0,ST,98,N,0.0,Up,0
3,0.408163,F,ASY,0.69,0.354892,0,Normal,108,Y,1.5,Flat,1
4,0.530612,M,NAP,0.75,0.323383,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,M,TA,0.55,0.437811,0,Normal,132,N,1.2,Flat,1
914,0.816327,M,ASY,0.72,0.320066,1,Normal,141,N,3.4,Flat,1
915,0.591837,M,ASY,0.65,0.217247,0,Normal,115,Y,1.2,Flat,1
916,0.591837,F,ATA,0.65,0.391376,0,LVH,174,N,0.0,Flat,1
917,0.204082,M,NAP,0.69,0.290216,0,Normal,173,N,0.0,Up,0

In [30]:
standardize = StandardScaler()
data[['MaxHR', 'Oldpeak']] = pd.DataFrame(standardize.fit_transform(data[['MaxHR', 'Oldpeak']]))
data = data.rename(columns={
    'MaxHR': 'MaxHR_standardized', 
    'Oldpeak': 'Oldpeak_standardized'
})
data

,Age_normalized,Gender,ChestPainType,RestingBP_normalized,Cholesterol,FastingBS,RestingECG,MaxHR_standardized,ExerciseAngina,Oldpeak_standardized,ST_Slope,HeartDisease
0,0.244898,M,ATA,0.70,0.479270,0,Normal,1.382928,N,-0.832432,Up,0
1,0.428571,F,NAP,0.80,0.298507,0,Normal,0.754157,N,0.105664,Flat,1
2,0.183673,M,ATA,0.65,0.469320,0,ST,-1.525138,N,-0.832432,Up,0
3,0.408163,F,ASY,0.69,0.354892,0,Normal,-1.132156,Y,0.574711,Flat,1
4,0.530612,M,NAP,0.75,0.323383,0,Normal,-0.581981,N,-0.832432,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,M,TA,0.55,0.437811,0,Normal,-0.188999,N,0.293283,Flat,1
914,0.816327,M,ASY,0.72,0.320066,1,Normal,0.164684,N,2.357094,Flat,1
915,0.591837,M,ASY,0.65,0.217247,0,Normal,-0.857069,Y,0.293283,Flat,1
916,0.591837,F,ATA,0.65,0.391376,0,LVH,1.461525,N,-0.832432,Flat,1
917,0.204082,M,NAP,0.69,0.290216,0,Normal,1.422226,N,-0.832432,Up,0

In [31]:
print(data['Oldpeak_standardized'].min())
print(data['Oldpeak_standardized'].max())

-3.2714817866091797
4.983762314391507

In [32]:
encoder = OneHotEncoder(sparse_output=False)

columns = ['Gender', 'FastingBS', 'ExerciseAngina', 'ST_Slope']
encoded = encoder.fit_transform(data[columns])
encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(columns),
    index=data.index
)

data = pd.concat(
    [data.drop(columns=columns), encoded_df],
    axis=1
)

data

,Age_normalized,ChestPainType,RestingBP_normalized,Cholesterol,RestingECG,MaxHR_standardized,Oldpeak_standardized,HeartDisease,Gender_F,Gender_M,FastingBS_0,FastingBS_1,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,0.244898,ATA,0.70,0.479270,Normal,1.382928,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.428571,NAP,0.80,0.298507,Normal,0.754157,0.105664,1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.183673,ATA,0.65,0.469320,ST,-1.525138,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.408163,ASY,0.69,0.354892,Normal,-1.132156,0.574711,1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.530612,NAP,0.75,0.323383,Normal,-0.581981,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,TA,0.55,0.437811,Normal,-0.188999,0.293283,1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
914,0.816327,ASY,0.72,0.320066,Normal,0.164684,2.357094,1,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
915,0.591837,ASY,0.65,0.217247,Normal,-0.857069,0.293283,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
916,0.591837,ATA,0.65,0.391376,LVH,1.461525,-0.832432,1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
917,0.204082,NAP,0.69,0.290216,Normal,1.422226,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [33]:
ordinal = OrdinalEncoder(
    categories=[['TA', 'ATA', 'NAP', 'ASY']]
)

data[['ChestPainType']] = pd.DataFrame(ordinal.fit_transform(data[['ChestPainType']]))
data

,Age_normalized,ChestPainType,RestingBP_normalized,Cholesterol,RestingECG,MaxHR_standardized,Oldpeak_standardized,HeartDisease,Gender_F,Gender_M,FastingBS_0,FastingBS_1,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,0.244898,1.0,0.70,0.479270,Normal,1.382928,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.428571,2.0,0.80,0.298507,Normal,0.754157,0.105664,1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.183673,1.0,0.65,0.469320,ST,-1.525138,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.408163,3.0,0.69,0.354892,Normal,-1.132156,0.574711,1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.530612,2.0,0.75,0.323383,Normal,-0.581981,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,0.0,0.55,0.437811,Normal,-0.188999,0.293283,1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
914,0.816327,3.0,0.72,0.320066,Normal,0.164684,2.357094,1,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
915,0.591837,3.0,0.65,0.217247,Normal,-0.857069,0.293283,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
916,0.591837,1.0,0.65,0.391376,LVH,1.461525,-0.832432,1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
917,0.204082,2.0,0.69,0.290216,Normal,1.422226,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [36]:
data['RestingECG'] = data['RestingECG'].map({'Normal': 'low', 'LVH': 'medium', 'ST': 'high'})
data

,Age_normalized,ChestPainType,RestingBP_normalized,Cholesterol,RestingECG,MaxHR_standardized,Oldpeak_standardized,HeartDisease,Gender_F,Gender_M,FastingBS_0,FastingBS_1,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,0.244898,1.0,0.70,0.479270,low,1.382928,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.428571,2.0,0.80,0.298507,low,0.754157,0.105664,1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.183673,1.0,0.65,0.469320,high,-1.525138,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.408163,3.0,0.69,0.354892,low,-1.132156,0.574711,1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.530612,2.0,0.75,0.323383,low,-0.581981,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,0.0,0.55,0.437811,low,-0.188999,0.293283,1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
914,0.816327,3.0,0.72,0.320066,low,0.164684,2.357094,1,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
915,0.591837,3.0,0.65,0.217247,low,-0.857069,0.293283,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
916,0.591837,1.0,0.65,0.391376,medium,1.461525,-0.832432,1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
917,0.204082,2.0,0.69,0.290216,low,1.422226,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [37]:
scaler = MinMaxScaler()

data[['ChestPainType']] = pd.DataFrame(scalar.fit_transform(data[['ChestPainType']]))
data

,Age_normalized,ChestPainType,RestingBP_normalized,Cholesterol,RestingECG,MaxHR_standardized,Oldpeak_standardized,HeartDisease,Gender_F,Gender_M,FastingBS_0,FastingBS_1,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,0.244898,0.333333,0.70,0.479270,low,1.382928,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.428571,0.666667,0.80,0.298507,low,0.754157,0.105664,1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.183673,0.333333,0.65,0.469320,high,-1.525138,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.408163,1.000000,0.69,0.354892,low,-1.132156,0.574711,1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.530612,0.666667,0.75,0.323383,low,-0.581981,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,0.000000,0.55,0.437811,low,-0.188999,0.293283,1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
914,0.816327,1.000000,0.72,0.320066,low,0.164684,2.357094,1,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
915,0.591837,1.000000,0.65,0.217247,low,-0.857069,0.293283,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
916,0.591837,0.333333,0.65,0.391376,medium,1.461525,-0.832432,1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
917,0.204082,0.666667,0.69,0.290216,low,1.422226,-0.832432,0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0