In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('Heart_Dataset.csv')
data

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [ ]:
data.isnull().sum()

# To drop null row:
data = data.dropna()

# To drop a column
data = data.drop(columns=['Oldpeak'])

from sklearn.impute import SimpleImputer

# Different null value fillers
imputer = SimpleImputer(strategy='mean')
imputer = SimpleImputer(strategy='median')
imputer = SimpleImputer(strategy='most_frequent')

data[['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']] = imputer.fit_transform(
    data[['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']]
)

Age               0
Gender            0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [24]:
print(data['Age'].max())
print(data['Age'].min())

77
28

In [25]:
data['Age'] = ((data['Age'] - data['Age'].min())/(data['Age'].max() - data['Age'].min()))
data

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,0.244898,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,0.428571,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,0.183673,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,0.408163,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,0.530612,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,0.816327,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,0.591837,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,0.591837,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,0.204082,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [26]:
print(data['Age'].max())
print(data['Age'].min())

1.0
0.0

In [27]:
data = pd.get_dummies(data, columns=['Gender'])
data

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Gender_F,Gender_M
0,0.244898,ATA,140,289,0,Normal,172,N,0.0,Up,0,False,True
1,0.428571,NAP,160,180,0,Normal,156,N,1.0,Flat,1,True,False
2,0.183673,ATA,130,283,0,ST,98,N,0.0,Up,0,False,True
3,0.408163,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,True,False
4,0.530612,NAP,150,195,0,Normal,122,N,0.0,Up,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,TA,110,264,0,Normal,132,N,1.2,Flat,1,False,True
914,0.816327,ASY,144,193,1,Normal,141,N,3.4,Flat,1,False,True
915,0.591837,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,False,True
916,0.591837,ATA,130,236,0,LVH,174,N,0.0,Flat,1,True,False
917,0.204082,NAP,138,175,0,Normal,173,N,0.0,Up,0,False,True

In [28]:
data['RestingBP'] = ((data['RestingBP'] - data['RestingBP'].min())/(data['RestingBP'].max() - data['RestingBP'].min()))
data['Cholesterol'] = ((data['Cholesterol'] - data['Cholesterol'].min())/(data['Cholesterol'].max() - data['Cholesterol'].min()))
data['MaxHR'] = ((data['MaxHR'] - data['MaxHR'].min())/(data['MaxHR'].max() - data['MaxHR'].min()))
data['Oldpeak'] = ((data['Oldpeak'] - data['Oldpeak'].min())/(data['Oldpeak'].max() - data['Oldpeak'].min()))
data

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Gender_F,Gender_M
0,0.244898,ATA,0.70,0.479270,0,Normal,0.788732,N,0.295455,Up,0,False,True
1,0.428571,NAP,0.80,0.298507,0,Normal,0.676056,N,0.409091,Flat,1,True,False
2,0.183673,ATA,0.65,0.469320,0,ST,0.267606,N,0.295455,Up,0,False,True
3,0.408163,ASY,0.69,0.354892,0,Normal,0.338028,Y,0.465909,Flat,1,True,False
4,0.530612,NAP,0.75,0.323383,0,Normal,0.436620,N,0.295455,Up,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,TA,0.55,0.437811,0,Normal,0.507042,N,0.431818,Flat,1,False,True
914,0.816327,ASY,0.72,0.320066,1,Normal,0.570423,N,0.681818,Flat,1,False,True
915,0.591837,ASY,0.65,0.217247,0,Normal,0.387324,Y,0.431818,Flat,1,False,True
916,0.591837,ATA,0.65,0.391376,0,LVH,0.802817,N,0.295455,Flat,1,True,False
917,0.204082,NAP,0.69,0.290216,0,Normal,0.795775,N,0.295455,Up,0,False,True

In [29]:
print(data['ExerciseAngina'].value_counts())
print(data['RestingECG'].value_counts())
print(data['ChestPainType'].value_counts())

ExerciseAngina
N    547
Y    371
Name: count, dtype: int64
RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64
ChestPainType
ASY    496
NAP    203
ATA    173
TA      46
Name: count, dtype: int64

In [30]:
data = pd.get_dummies(data, columns=['ExerciseAngina'])
data = pd.get_dummies(data, columns=['RestingECG'])
data = pd.get_dummies(data, columns=['ST_Slope'])
data

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Gender_F,Gender_M,ExerciseAngina_N,ExerciseAngina_Y,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,0.244898,ATA,0.70,0.479270,0,0.788732,0.295455,0,False,True,True,False,False,True,False,False,False,True
1,0.428571,NAP,0.80,0.298507,0,0.676056,0.409091,1,True,False,True,False,False,True,False,False,True,False
2,0.183673,ATA,0.65,0.469320,0,0.267606,0.295455,0,False,True,True,False,False,False,True,False,False,True
3,0.408163,ASY,0.69,0.354892,0,0.338028,0.465909,1,True,False,False,True,False,True,False,False,True,False
4,0.530612,NAP,0.75,0.323383,0,0.436620,0.295455,0,False,True,True,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,TA,0.55,0.437811,0,0.507042,0.431818,1,False,True,True,False,False,True,False,False,True,False
914,0.816327,ASY,0.72,0.320066,1,0.570423,0.681818,1,False,True,True,False,False,True,False,False,True,False
915,0.591837,ASY,0.65,0.217247,0,0.387324,0.431818,1,False,True,False,True,False,True,False,False,True,False
916,0.591837,ATA,0.65,0.391376,0,0.802817,0.295455,1,True,False,True,False,True,False,False,False,True,False
917,0.204082,NAP,0.69,0.290216,0,0.795775,0.295455,0,False,True,True,False,False,True,False,False,False,True

In [31]:
data['ChestPainType'] = data['ChestPainType'].map({'ATA': 1, 'NAP': 2, 'TA': 3, 'ASY': 4 })
data

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Gender_F,Gender_M,ExerciseAngina_N,ExerciseAngina_Y,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,0.244898,1,0.70,0.479270,0,0.788732,0.295455,0,False,True,True,False,False,True,False,False,False,True
1,0.428571,2,0.80,0.298507,0,0.676056,0.409091,1,True,False,True,False,False,True,False,False,True,False
2,0.183673,1,0.65,0.469320,0,0.267606,0.295455,0,False,True,True,False,False,False,True,False,False,True
3,0.408163,4,0.69,0.354892,0,0.338028,0.465909,1,True,False,False,True,False,True,False,False,True,False
4,0.530612,2,0.75,0.323383,0,0.436620,0.295455,0,False,True,True,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,3,0.55,0.437811,0,0.507042,0.431818,1,False,True,True,False,False,True,False,False,True,False
914,0.816327,4,0.72,0.320066,1,0.570423,0.681818,1,False,True,True,False,False,True,False,False,True,False
915,0.591837,4,0.65,0.217247,0,0.387324,0.431818,1,False,True,False,True,False,True,False,False,True,False
916,0.591837,1,0.65,0.391376,0,0.802817,0.295455,1,True,False,True,False,True,False,False,False,True,False
917,0.204082,2,0.69,0.290216,0,0.795775,0.295455,0,False,True,True,False,False,True,False,False,False,True

In [32]:
data['ChestPainType'] = ((data['ChestPainType'] - data['ChestPainType'].min())/(data['ChestPainType'].max() - data['ChestPainType'].min()))
data

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Gender_F,Gender_M,ExerciseAngina_N,ExerciseAngina_Y,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,0.244898,0.000000,0.70,0.479270,0,0.788732,0.295455,0,False,True,True,False,False,True,False,False,False,True
1,0.428571,0.333333,0.80,0.298507,0,0.676056,0.409091,1,True,False,True,False,False,True,False,False,True,False
2,0.183673,0.000000,0.65,0.469320,0,0.267606,0.295455,0,False,True,True,False,False,False,True,False,False,True
3,0.408163,1.000000,0.69,0.354892,0,0.338028,0.465909,1,True,False,False,True,False,True,False,False,True,False
4,0.530612,0.333333,0.75,0.323383,0,0.436620,0.295455,0,False,True,True,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.346939,0.666667,0.55,0.437811,0,0.507042,0.431818,1,False,True,True,False,False,True,False,False,True,False
914,0.816327,1.000000,0.72,0.320066,1,0.570423,0.681818,1,False,True,True,False,False,True,False,False,True,False
915,0.591837,1.000000,0.65,0.217247,0,0.387324,0.431818,1,False,True,False,True,False,True,False,False,True,False
916,0.591837,0.000000,0.65,0.391376,0,0.802817,0.295455,1,True,False,True,False,True,False,False,False,True,False
917,0.204082,0.333333,0.69,0.290216,0,0.795775,0.295455,0,False,True,True,False,False,True,False,False,False,True