## The Heart Dataset

File name: 'Heart_Dataset.csv'

This dataset has been obtained from Kaggle: https://www.kaggle.com/fedesoriano/heart-failure-prediction

The data contains 918 observations with 12 attributes as described below:
1. Age: patient's age, range: 28 to 77.
2. Sex: patient's gender, M(79%), F(21%).
3. ChestPainType: ASY (54%), NAP (22%), Other(24%).
4. RestingBP: resting blood pressure, range: 0 to 200.
5. Cholestrol: serum cholestrol, range: 0 to 603.
6. FastingBS: fasting blood sugar, 0 or 1.
7. RestingECG: resting electrocardiogram results, Normal (60%), LVH (20%), Other (19%).
8. MaxHR: maximum heart rate achieved, range: 60 to 202.
9. ExerciseAngina: exercise induced angina, true(317-40%), false (547-60%).
10. OldPeak: old peak=ST, range: -2.6 to 6.2.
11. ST_Slope: ST slope, Up or flat.
12. HeartDisease: target, 1 or 0.

Last column indicates presence of heart disease given the remaining 11 attributes. 

This is a binary classification problem.

Contains categorical data, otherwise the dataset is clean.

## Loading and Exploring Dataset

In [1]:
import pandas as pd
# Reading the file into a dataframe
PATH='D:\Course Lectures\Artificial Intelligence TE CIS FALL 2026\Practicals\Practicals\Datasets'
data=pd.read_csv(f'{PATH}/Heart_Dataset.csv')
# Displaying the read contents
data

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [2]:
# Finding type of the variable 'data'
type(data)

pandas.DataFrame

## Cleaning Data

In [3]:
# Displaying info about various columns of 'data'
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Gender          918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 97.6 KB

In [4]:
# Finding counts of possible values in a column
data['ExerciseAngina'].value_counts()

ExerciseAngina
N    547
Y    371
Name: count, dtype: int64

In [6]:
data['RestingBP'].value_counts()

RestingBP
120    132
130    118
140    107
110     58
150     55
      ...
174      1
117      1
192      1
129      1
164      1
Name: count, Length: 67, dtype: int64

In [7]:
# Finding maximum value in a column
data['RestingBP'].max()

np.int64(200)

In [8]:
# Finding minimum value in a column
data['RestingBP'].min()

np.int64(0)

In [9]:
# Getting count for a specific value in a column
data['RestingBP'].value_counts().get(0)

np.int64(1)

In [10]:
# Dropping all rows where 'RestingBP' is less than 30 
# Saving in a new variable 
data2= data[(data['RestingBP'] >= 30)]
data2

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [11]:
data2['RestingBP'].min()

np.int64(80)

In [12]:
# Dropping a whole column
data2.drop(['RestingBP'], axis=1)

,Age,Gender,ChestPainType,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,175,0,Normal,173,N,0.0,Up,0

In [13]:
# Original DataFrame 'data' remains unchanged
data

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

## Encoding Categorical Data

Consider the 'ExerciseAngina' column first and apply dummy variable encoding.
- This is a binary variable as its presence counts towards increased risk of heart disease and absence means otherwise.
- Can be ecoded using dummy variable encoding.

In [14]:
data['ExerciseAngina'].value_counts()

ExerciseAngina
N    547
Y    371
Name: count, dtype: int64

In [15]:
#The simplest way to encode 'ExerciseAngina' as dummy varaible is to use the map method. 
data['ExerciseAngina'] = data['ExerciseAngina'].map({'N': 0, 'Y': 1})
data

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,0,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,0,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,0,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,1,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,0,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,0,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,0,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,1,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,0,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,0,0.0,Up,0

Now consider the 'ChestPainType' column and apply ordinal encoding.

In [16]:
data['ChestPainType'].value_counts()

ChestPainType
ASY    496
NAP    203
ATA    173
TA      46
Name: count, dtype: int64

Let us use Ordinal encoding as follows:
- TA (typical angina): 1
- ATA (atypical angina): 2
- NAP (non-anginal pain): 3
- ASY (asymptomatic): 4

In [17]:
data['ChestPainType'] = data['ChestPainType'].map({'TA':1, 'ATA':2, 'NAP':3, 'ASY': 4})
data

,Age,Gender,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,2,140,289,0,Normal,172,0,0.0,Up,0
1,49,F,3,160,180,0,Normal,156,0,1.0,Flat,1
2,37,M,2,130,283,0,ST,98,0,0.0,Up,0
3,48,F,4,138,214,0,Normal,108,1,1.5,Flat,1
4,54,M,3,150,195,0,Normal,122,0,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,1,110,264,0,Normal,132,0,1.2,Flat,1
914,68,M,4,144,193,1,Normal,141,0,3.4,Flat,1
915,57,M,4,130,131,0,Normal,115,1,1.2,Flat,1
916,57,F,2,130,236,0,LVH,174,0,0.0,Flat,1
917,38,M,3,138,175,0,Normal,173,0,0.0,Up,0

Now consider the 'Gender' column and apply one-hot encoding.

In [5]:
#get_dummies is a simple method in pandas which can achieve this task.
data=pd.get_dummies(data, columns=['Gender'])
#The resulting table has two dummy variable encoded columns Gender_F and Gender_M, in place of one column Gender

## Scaling (Normalization)

In [20]:
#Let us normalize the 'RestingBP' column using the normalization
data['RestingBP']=(data['RestingBP']-data['RestingBP'].min())/(data['RestingBP'].max()-data['RestingBP'].min())
data

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Gender_F,Gender_M
0,40,2,0.70,289,0,Normal,172,0,0.0,Up,0,False,True
1,49,3,0.80,180,0,Normal,156,0,1.0,Flat,1,True,False
2,37,2,0.65,283,0,ST,98,0,0.0,Up,0,False,True
3,48,4,0.69,214,0,Normal,108,1,1.5,Flat,1,True,False
4,54,3,0.75,195,0,Normal,122,0,0.0,Up,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,0.55,264,0,Normal,132,0,1.2,Flat,1,False,True
914,68,4,0.72,193,1,Normal,141,0,3.4,Flat,1,False,True
915,57,4,0.65,131,0,Normal,115,1,1.2,Flat,1,False,True
916,57,2,0.65,236,0,LVH,174,0,0.0,Flat,1,True,False
917,38,3,0.69,175,0,Normal,173,0,0.0,Up,0,False,True

In [21]:
#Let us check the min and max value of this normalized column now.
print('Minimum value is',data['RestingBP'].min())
print('Maximum value is',data['RestingBP'].max())

Minimum value is 0.0
Maximum value is 1.0

In [22]:
# An alternate way is to use methods from sklearn package.
# Let us use this alternate method now to normalize 'Cholesterol' column.
# It is a 2-step process. We define an object of MinMaxScaler type first,
# and then call the method fit_transform on this object to perform normalization.

from sklearn.preprocessing import MinMaxScaler

# Defining min-max scaler object
minmax_scaler = MinMaxScaler()

#Normailize data 
data['Cholesterol']=pd.DataFrame(minmax_scaler.fit_transform(data[['Cholesterol']]))
#Note that fit_transform method returns a ndarray, so we need to typecast it back to dataframe before placong it back into out dataset.

data

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Gender_F,Gender_M
0,40,2,0.70,0.479270,0,Normal,172,0,0.0,Up,0,False,True
1,49,3,0.80,0.298507,0,Normal,156,0,1.0,Flat,1,True,False
2,37,2,0.65,0.469320,0,ST,98,0,0.0,Up,0,False,True
3,48,4,0.69,0.354892,0,Normal,108,1,1.5,Flat,1,True,False
4,54,3,0.75,0.323383,0,Normal,122,0,0.0,Up,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,0.55,0.437811,0,Normal,132,0,1.2,Flat,1,False,True
914,68,4,0.72,0.320066,1,Normal,141,0,3.4,Flat,1,False,True
915,57,4,0.65,0.217247,0,Normal,115,1,1.2,Flat,1,False,True
916,57,2,0.65,0.391376,0,LVH,174,0,0.0,Flat,1,True,False
917,38,3,0.69,0.290216,0,Normal,173,0,0.0,Up,0,False,True

In [6]:
#Let us check the min and max value of this normalized column now.
print('Minimum value is',data['Cholesterol'].min())
print('Maximum value is',data['Cholesterol'].max())

Minimum value is 0
Maximum value is 603

## Saving the Clean Data

In [23]:
# All the changes that we have made so far are done on the dataframe, and not in the original csv file.
# The to_csv method can be used to save the dataframe into a csv file.
data.to_csv(f'{PATH}/Heart_Dataset_Clean.csv')